### ISSUE TITLE
Setup Codeclimate analysis

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/getmac#11]
Setup and configure CodeClimate ([See configuration in ADLES for reference](https://github.com/GhostofGoes/ADLES/blob/master/.codeclimate.yml))

**Comment by hargoniX** [comment]
So... if i got this correct this is just copying a file from one of your other repos to here?

**Comment by GhostofGoes** [comment]
Basically. However, it's two years old and needs updating, plus tweaks to make it more relevant and less harsh on the chaos and horrible coding practices that is `getmac.py`.

**Comment by GhostofGoes** [comment]
Decided against this. It's rather nitpicky and isn't adding anything over what is already being done in Tox (`tox -e check`).
