### ISSUE TITLE
Complete unit test coverage

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/getmac#16]
Complete coverage of all methods, including `_popen()`. This will require mocking, and some other related hackery I don't have experience with yet.

**Comment by cyberhobbes** [comment]
Are we using the mock library? How do we add include this module without having the user install it?

I would like to understand how to write unittest. I believe we need to use mock since the functions are not within a class. I am trying to figure out how to access `_popen()`.

**Comment by cyberhobbes** [comment]
I have the answer to the questions from @Frizz925 update at https://github.com/GhostofGoes/getmac/commit/df670f8203cd81580fce5542ff5c24b3fe9095f6

**Comment by GhostofGoes** [comment]
Sorry for not replying earlier. What is the answer?

**Comment by cyberhobbes** [comment]
Hi Chris,

His answer shows that we can use the unittest mock or mock library. The user will always need to install the module, but we could now add a requirements.txt file to specify which mock version to use.

His example was what I wanted to learn and achieve.
