### ISSUE TITLE
Performance profiling

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/getmac#23]
Profile the execution and memory performance and add the results in a directory `profiling/`. Need to figure out where bottlenecks are across Python versions and operating systems ("platforms").

**Comment by nilssohn** [comment]
What platforms are priorities?

**Comment by GhostofGoes** [comment]
Yes, that would be great. Profiling is really needed for any platform, including Linux distros and Windows. General functionality testing is more critical for OSX right now than profiling (not going to try to optimize for a platform we can't even test).

**Comment by nilssohn** [comment]
I'll try to test a variety with VMs.
