### ISSUE TITLE
Latest release on pypi.org is not current

### ISSUE THREAD

**Issue by mihalski** [GhostofGoes/getmac#32]
https://pypi.org/project/get-mac/

**Comment by GhostofGoes** [comment]
@mihalski Hello, `get-mac` has been renamed to `getmac`. The new PyPI page is here: https://pypi.org/project/getmac/

The description on the old version of the project you link states this:

"'get-mac' has changed names and moved to 'getmac' on PyPI. Please update your dependencies or notify the maintainer of the application."

In hindsight, I see I have made a mistake with "notify the maintainer of the application". What I intended to say was "notify the maintainer of the application or library that depends on this package".

**Comment by mihalski** [comment]
🤦‍♂️
