### ISSUE TITLE
Understanding test failures

### ISSUE THREAD

**Issue by colemickens** [GhostofGoes/getmac#55]
**Describe the bug**

I'm packaging `getmac` for Nix / NixOS: https://github.com/NixOS/nixpkgs/pull/78015.
We try to enable unit tests for other python packages for good hygiene. I cannot do this currently for `getmac` as some tests are failing.

I'm just looking for suggestions on what I'm doing wrong. I'm getting a type error which makes me think that there is possibly a problem with an assumption the test is making. (For example, I'm wondering if our sandbox prevents the code from seeing any MAC address, hence `None` instead of `<string>`.

Do you have any suggestions? Shall we disable these specific tests? Is it worth modifying the tests to have a fallback dummy MAC or does it defeat the point of the test entirely? Thanks.

**To Reproduce**
1. Install `nix`
2. Run `nix-build https://github.com/colemickens/nixpkgs/archive/nixpkgs-ha-pkgs-getmac.tar.gz -A python3Packages.getmac`

**Expected behavior**

The package is built, and runs tests successfully during build.

**Actual behavior**

```

=================================== FAILURES ===================================
_____________________________ test_cli_main_basic ______________________________
tests/test_cli.py:20: in test_cli_main_basic
    assert run_cmd(BASE_CMD) == get_mac_address()
E   AssertionError: assert '' == None
E    +  where '' = run_cmd(['/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/bin/python3.7', '-m', 'getmac'])
E    +  and   None = get_mac_address()
____________________________ test_cli_main_verbose _____________________________
tests/test_cli.py:24: in test_cli_main_verbose
    assert get_mac_address() in run_cmd(BASE_CMD + ["--verbose"])
E   TypeError: 'in <string>' requires string as left operand, not NoneType
_____________________________ test_cli_main_debug ______________________________
tests/test_cli.py:28: in test_cli_main_debug
    assert get_mac_address() in run_cmd(BASE_CMD + ["--verbose", "--debug"])
E   TypeError: 'in <string>' requires string as left operand, not NoneType
________________________ test_cli_multiple_debug_levels ________________________
tests/test_cli.py:49: in test_cli_multiple_debug_levels
    assert get_mac_address() in run_cmd(BASE_CMD + ["-v", "-dd"])
E   TypeError: 'in <string>' requires string as left operand, not NoneType

```

**System info**
(please complete the following information):
 - OS name: [e.g. Windows 10 x64]
 - OS Version: [1804 build 17134]
 - Python version: [3.6.5 x64]

**Additional context**

**Comment by GhostofGoes** [comment]
Yeah, disabling the test is probably the best solution.

Essentially, it's validating that CLI is operating correctly, by comparing the MAC returned by the internal API with the terminal output. If the test is running in a sandbox then failure is expected, as it's relying on `get_mac_address()` to operate which requires access to system calls. The CLI is not critical by any means and is mainly around as a handy utility and for testing/debugging.

**Comment by colemickens** [comment]
Great, thanks for confirming!
