### ISSUE TITLE
Tox code quality checks fail on clean clone of repo

### ISSUE THREAD

**Issue by FlantasticDan** [GhostofGoes/getmac#66]
**Describe the bug**
`tox -e check` fails in several places on a fresh clone of the repository.

**To Reproduce**
1. Clone Repo: `git clone https://github.com/GhostofGoes/getmac.git`
2. Install developer tools:
```
python -m pip install --user -U tox
python -m pip install -e .
```
3. Run Code Quality Checks `tox -e check`

**Expected behavior**
All tests pass.

**System info**
(please complete the following information):
 - OS name: Ubuntu on Raspberry Pi 4
 - OS Version: 20.04
 - Python version: 3.9.5

**Additional context**
It seems two of the tests in the code quality suite fail:

`check-manifest` fails and exports the following:
```
lists of files in version control and sdist do not match!
missing from sdist:
  docs/Makefile
  docs/TODO.md
  docs/conf.py
  docs/packaging.md
  docs/releasing.md
  docs/requirements.txt
suggested MANIFEST.in rules:
  recursive-include docs *.md
  recursive-include docs *.py
  recursive-include docs *.txt
  recursive-include docs Makefile
ERROR: InvocationError for command /home/ubuntu/dev/getmac/.tox/check/bin/check-manifest . (exited with code 1)
```
This error is easily fixed by appending the output's suggestion to MANIFEST.in, which allows tox to continue to the next failed test, `flake8`:
```
getmac/getmac.py:165:1: B902 blind except Exception: statement
        except Exception:
^
getmac/getmac.py:301:1: B902 blind except Exception: statement
    except Exception:
^
getmac/getmac.py:352:1: B902 blind except Exception: statement
    except Exception:
^
getmac/getmac.py:396:20: BLK100 Black would make changes.
    return _search(r"^%s$" % MAC_RE_COLON, _popen("arping", "-r -C 1 -c 1 %s" % host),)
                   ^
getmac/getmac.py:413:5: B014 Redundant exception types in `except (OSError, IOError):`.  Write `except OSError:`, which catches exactly the same exceptions.
    except (OSError, IOError):  # This is IOError on Python 2.7
    ^
getmac/getmac.py:585:1: B902 blind except Exception: statement
        except Exception as ex:
^
```
These errors can be suppressed by adding `B902, BLK100, B014` to the flake8 ignore attribute in `tox.ini`.

Not sure if suppressing these errors is the desired outcome, or if I'm the only one experiencing them.  I can open a pull request   that implements my suppressions if that's useful.

**Comment by GhostofGoes** [comment]
Oh gosh, it's been ages since any checks have been run on the master branch (last CI build was May 9, 2020). The linting dependencies aren't version-pinned so updates to them have probably resulted in this.

All the suggested changes seem reasonable, feel free to open a PR. If you could make the changes on a per-line basis (e.g. `noqa: BLK100`) instead of in `tox.ini` that would be preferred. All of the "issues" highlighted are intentional (except for the black formatting), for example handling the general `Exception` case.
