### ISSUE TITLE
Fail to run on Kali Linux 2021.3

### ISSUE THREAD

**Issue by tanducmai** [GhostofGoes/getmac#68]
**Describe the bug**
Although I have "pip install getmac" in the terminal, when I "import getmac" in my Python program, it keeps reporting no module named getmac.

**System info**
(please complete the following information):
 - OS name: Kali Linux
 - OS Version: 2021.3
 - Python version: 3.9.7 x64

**Comment by GhostofGoes** [comment]
I haven't used modern Kali, but I imagine `pip` still refers to Python 2's PIP and `pip3` refers to Python 3's pip. 

Try running `pip3 install getmac`, and ensure it appears in the output of `pip3 list`.

**Comment by GhostofGoes** [comment]
No response from opener, sounds like a environment-related issue, closing.
