### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/getmac#9]
Build a RPM package for Linux distributions that use `yum` (RHEL, CentOS, Fedora). Need to make something that can be distributed on EPEL and meets the guidelines for CentOS and Fedora.

**Comment by hargoniX** [comment]
I'd like to work on this.

I assume the best idea would be to run some script from inside travis ci. What I am not sure about is where to put the package file after that is done, shall it just upload as an artifact or somewhere else?

**Comment by GhostofGoes** [comment]
The reason behind wanting a RPM (and a DEB) is to usable on Linux distributions. If another Python package needs to depend on this, it has to be a package. Furthermore, and especially for RHEL systems, pip may not even be installed, which necessitates using a package.

However, I've never published to EPEL (let alone any public package repo beyond PyPI), so I don't know what the process is.  For now, I'd just like to get generation working, so I can at least generate and include the .rpm with the release artifacts. 

We could do some automatic generation in the CI too to make sure it isn't breaking. There is no automated deployment currently though, so it won't really do anything for now.

**Comment by hargoniX** [comment]
See PR #29

**Comment by GhostofGoes** [comment]
This is definitely done
